# -*- coding: utf-8 -*-
"""Salary_Predictor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1en6wbkjLJZ_TmiRJgPd7hSMOjIJR8W9e
"""

import pandas as pd

dataset = pd.read_csv('Salary_Data.csv')
# print(dataset)

X = dataset.iloc[:,0].values    # First column
y = dataset.iloc[:,1].values    # Second column

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 1/3)

# Test set 1/3rd of the dataset (10 samples)
print(len(X_train))
print(len(X_test))
print(len(Y_train))
print(len(Y_test))

from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
X_train = X_train.reshape(-1, 1)
Y_train = Y_train.reshape(-1, 1)
X_test = X_test.reshape(-1, 1)
Y_test = Y_test.reshape(1, -1)

regressor.fit(X_train, Y_train)

y_pred = regressor.predict(X_test)

print(y_pred)
print(Y_test)

import matplotlib.pyplot as plt
plt.scatter(X_train, Y_train, color = "blue")
plt.plot(X_train, regressor.predict(X_train), color = "red")
plt.title('Train set')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

import matplotlib.pyplot as plt
# plot the actual data points of test set
plt.scatter(X_test, Y_test, color = 'blue')
# plot the regression line (same as above)
plt.plot(X_train, regressor.predict(X_train), color='red')
plt.title('Test set')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

